---
include:
  #- board: nice_nano_v2
  #  shield: corne_central_left
  #  artifact-name: corne_central_left
  - board: nice_nano_v2
    shield: corne_peripheral_left hammerbeam_display
    artifact-name: corne_peripheral_left
  - board: nice_nano_v2
    shield: corne_peripheral_right hammerbeam_display
    artifact-name: corne_peripheral_right
  - board: nice_nano_v2
    shield: corne_central_dongle dongle_display
    artifact-name: corne_central_dongle
  #- board: nice_nano_v2
  #  shield: settings_reset
  #  artifact-name: reset_nice_nano